name: Update Niconico Stats

on:
  repository_dispatch:
    types: [update-stats]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: パッケージのインストール
        run: npm install

      - name: 取得スクリプトの実行
        run: node fetchStats.js

      - name: 変更されたデータのコミットとプッシュ
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.json
          
          if ! git diff --staged --quiet; then
            git commit -m "Update stats data"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit."
          fi
